import type { MiniGameModule } from './types'
import { createController } from './runtime/controllers'

type Definition = Omit<MiniGameModule, 'createController'>

const definitions: Definition[] = [
  {
    id: 'hoop-flight', slug: 'hoop-flight', title: 'Hoop Flight', kicker: 'GRAVITY RUN', icon: 'HF', category: 'Arcade Basketball',
    shortDescription: '탭으로 낙하 타이밍을 제어하며 끝없이 이어지는 림을 통과하세요.',
    fullDescription: '공은 계속 앞으로 이동하고 중력 때문에 아래로 떨어집니다. 탭으로 짧은 상승 힘을 더해 높이가 달라지는 림의 위에서 아래로 통과하세요. 림을 건드리지 않은 연속 클린샷은 득점 배율과 FIRE 연출을 키웁니다.',
    objective: '골대를 놓치지 않고 최대한 많은 림을 연속으로 통과해 최고 점수를 갱신하세요.',
    theme: { background: '#c9baa0', surface: '#282219', accent: '#ef4934', accent2: '#f3c64e', text: '#fffaf0', muted: '#8c7f69', headerStyle: 'dark' },
    controls: [{ label: '탭', description: '공에 즉시 위쪽 힘을 줍니다. 짧게 나누어 탭하면 높이를 세밀하게 유지할 수 있습니다.' }],
    scoringRules: [{ label: '일반 골', value: '림 사이를 위에서 아래로 통과하면 +1점' }, { label: '연속 클린', value: '림 접촉 없이 넣으면 1, 2, 3… 최대 5점까지 상승' }, { label: 'FIRE', value: '클린샷 3연속부터 불꽃 모드가 켜지며 배율은 계속 유지' }],
    failureConditions: ['공이 화면 아래 안전선을 벗어나면 비행이 종료됩니다.', '득점하지 못한 골대가 공 뒤로 지나가거나 공이 화면 왼쪽으로 밀려나면 종료됩니다.'],
    tips: ['공이 내려오기 시작한 뒤 한 번씩 탭하면 과도하게 높이 뜨는 것을 줄일 수 있습니다.', '천장에 닿아도 종료되지 않으므로 높은 골대를 앞두고 미리 상승해도 됩니다.', '림에 한 번이라도 닿으면 클린 콤보가 초기화됩니다.'],
  },
  {
    id: 'dunk-climb', slug: 'dunk-climb', title: 'Dunk Climb', kicker: 'AIM HIGHER', icon: 'DC', category: 'Skill Basketball',
    shortDescription: '궤적을 조준하고 벽 반사를 조합해 골대를 타고 계속 올라가세요.',
    fullDescription: '공을 잡아 뒤로 당기면 예상 이동 경로와 벽 반사 지점이 표시됩니다. 손을 놓아 반대 방향으로 발사하고 위쪽 골대에 넣으세요. 성공하면 현재 골대가 발판이 되고 더 높은 목표가 생성됩니다.',
    objective: '공을 떨어뜨리지 않고 위쪽 골대를 연속 공략해 도시 위로 최대한 높이 올라가세요.',
    theme: { background: '#f1f1f2', surface: '#e5e5e7', accent: '#f19a2b', accent2: '#e94b2f', text: '#222226', muted: '#8a8a90', headerStyle: 'dark' },
    controls: [{ label: '당기기', description: '공 주변을 누르고 최대 150px까지 당겨 방향과 힘을 정합니다. 점선은 벽 반사를 포함한 예상 경로입니다.' }, { label: '놓기', description: '당긴 반대 방향으로 공을 발사합니다. 18px보다 짧은 드래그는 취소됩니다.' }],
    scoringRules: [{ label: '기본 골', value: '목표 골대 통과 시 +1점' }, { label: '클린 콤보', value: '림 무접촉 연속 성공마다 +1, +2… 최대 +5 보너스' }, { label: '벽 반사', value: '벽을 한 번 이상 이용해 성공하면 추가 +1점' }],
    failureConditions: ['공이 목표 골대와 시작 골대를 모두 놓치고 화면 아래로 떨어지면 종료됩니다.'],
    tips: ['시작 골대로 다시 들어오면 SAVED 판정으로 공을 되돌려 받아 재도전할 수 있습니다.', '클린샷과 벽 반사를 동시에 성공하면 두 보너스가 함께 적용됩니다.', '공을 길게 당길수록 강해지지만, 가까운 골대에는 중간 세기가 더 안정적입니다.'],
  },
  {
    id: 'loop-hoops', slug: 'loop-hoops', title: 'Loop Hoops', kicker: 'SIDE TO SIDE', icon: 'LH', category: 'Loop Basketball',
    shortDescription: '화면 양쪽을 순환하며 제한 시간 안에 좌우 골대를 번갈아 공략하세요.',
    fullDescription: '탭할 때마다 공이 위로 튀고 현재 목표 골대 방향으로 속도가 붙습니다. 공은 좌우 화면 경계를 통과하면 반대편에서 자연스럽게 이어집니다. 골을 넣을 때마다 목표가 반대편으로 이동하고 타이머가 가득 찹니다.',
    objective: '줄어드는 타이머가 0이 되기 전에 좌우 골대에 계속 득점해 플레이 시간을 연장하세요.',
    theme: { background: '#60493c', surface: '#37251e', accent: '#16e8eb', accent2: '#ff198f', text: '#ffffff', muted: '#cdb7aa', headerStyle: 'dark' },
    controls: [{ label: '탭', description: '공을 즉시 위로 튕기고 현재 목표 골대 쪽으로 이동시킵니다.' }, { label: '좌우 루프', description: '양쪽 화면 경계를 넘으면 같은 높이와 속도를 유지한 채 반대편에서 이어집니다.' }],
    scoringRules: [{ label: '일반 골', value: '목표 림을 위에서 아래로 통과하면 +1점' }, { label: '클린 콤보', value: '림·천장·바닥 무접촉 연속 골은 1, 2, 3… 최대 5점' }, { label: '시간 충전', value: '득점할 때마다 타이머가 100%로 회복' }],
    failureConditions: ['화면 상단 타이머가 완전히 소진되면 게임이 종료됩니다.'],
    tips: ['화면 밖으로 나가는 것은 실수가 아니라 이동 수단입니다. 반대편 골대를 향한 지름길로 활용하세요.', '바닥은 자동으로 공을 튕겨 주지만 클린 콤보는 초기화됩니다.', '점수가 높아질수록 타이머가 더 빠르게 줄어드니 골 직후 다음 높이를 확인하세요.'],
  },
  {
    id: 'crossing-rush', slug: 'crossing-rush', title: 'Crossing Rush', kicker: 'ONE MORE STEP', icon: 'CR', category: 'Endless Crossing',
    shortDescription: '차량과 급류의 움직임을 읽고 한 칸씩 끝없는 길을 건너세요.',
    fullDescription: '상하좌우로 한 칸씩 이동하며 도로와 강을 통과합니다. 도로에서는 움직이는 차량을 피하고, 강에서는 통나무 위에 올라 함께 이동해야 합니다. 풀밭의 나무는 지나갈 수 없습니다.',
    objective: '차와 물을 피해 이전 최고 거리보다 더 멀리 전진하고 길 위의 코인을 수집하세요.',
    theme: { background: '#8ac43f', surface: '#183620', accent: '#fff36a', accent2: '#ff6c54', text: '#ffffff', muted: '#d9efbe', headerStyle: 'pixel' },
    controls: [{ label: '스와이프', description: '상하좌우로 한 칸 점프합니다. 나무가 있는 칸이나 화면 가장자리 밖으로는 이동하지 않습니다.' }, { label: '짧은 탭', description: '스와이프하지 않고 짧게 탭하면 앞쪽으로 한 칸 이동합니다.' }],
    scoringRules: [{ label: '최고 거리', value: '처음 도달한 앞쪽 행마다 +1점' }, { label: '코인', value: '코인이 있는 칸에 착지하면 +5점' }, { label: '후진·횡이동', value: '안전 확보에는 사용할 수 있지만 거리 점수는 없음' }],
    failureConditions: ['도로에서 차량과 부딪히면 종료됩니다.', '강에서 통나무가 없는 물에 착지하면 종료됩니다.', '통나무에 탄 채 화면 좌우 밖으로 떠밀려 나가면 종료됩니다.'],
    tips: ['차량과 통나무는 행마다 서로 다른 방향과 속도로 움직입니다.', '강을 건널 때는 도착 칸뿐 아니라 통나무가 이동할 방향까지 확인하세요.', '급할 때는 옆이나 뒤로 이동해 안전한 타이밍을 다시 만들 수 있습니다.'],
  },
  {
    id: 'neon-escape', slug: 'neon-escape', title: 'Neon Vault', kicker: 'DON’T STOP', icon: 'NV', category: 'Neon Maze',
    shortDescription: '멈출 수 없는 네온 미로에서 신호와 스위치를 모아 3개의 금고를 탈출하세요.',
    fullDescription: '스와이프하면 다음 벽이나 활성 펄스 게이트 직전까지 자동으로 미끄러집니다. 이동 경로의 신호·코인·스위치를 수집하고, 텔레포트와 방향을 90도 바꾸는 프리즘을 이용해 빨강·민트·보라 3스테이지를 탈출하세요.',
    objective: '각 스테이지의 모든 신호를 수집하고 스위치를 전부 켠 뒤 열린 출구에 도달하세요.',
    theme: { background: '#09051b', surface: '#10082e', accent: '#45ffe0', accent2: '#ff3ca6', text: '#f7f4ff', muted: '#9d92c5', headerStyle: 'neon' },
    controls: [{ label: '스와이프', description: '0.5초 안에 24px 이상 밀면 선택 방향으로 출발해 벽 직전까지 이동합니다. 이동 중에는 방향을 바꿀 수 없습니다.' }, { label: '특수 타일', description: '포털은 연결 지점으로 이동시키고, 프리즘은 진행 방향을 오른쪽 또는 왼쪽으로 90도 꺾습니다.' }],
    scoringRules: [{ label: '신호', value: '노란 신호 하나당 +1점' }, { label: '스위치', value: '스위치 활성화당 +5점' }, { label: '코인', value: '금고 코인 하나당 +10점' }, { label: '스테이지 탈출', value: '기본 +25점과 수집한 코인당 추가 +5점' }],
    failureConditions: ['활성 가시·레이저·펄스 게이트 또는 순찰자와 충돌하면 종료됩니다.', '보호막이 있다면 한 번의 충돌을 막고 해당 칸에서 즉시 멈춥니다.'],
    tips: ['펄스 게이트가 켜져 있을 때는 벽처럼 작동하므로 새로운 정지 지점으로 이용할 수 있습니다.', '출구는 모든 신호와 스위치를 처리하기 전까지 열리지 않습니다.', '보호막은 위험을 막는 동시에 이동을 중단시켜 새로운 경로를 만드는 데도 사용할 수 있습니다.'],
  },
  {
    id: 'perfect-stack', slug: 'perfect-stack', title: 'Perfect Stack', kicker: 'BUILD THE SKY', icon: 'PS', category: 'Precision Stack',
    shortDescription: '움직이는 블록을 정확히 맞춰 폭을 지키며 밤하늘 끝까지 탑을 쌓으세요.',
    fullDescription: '좌우로 움직이는 블록을 탭해 아래 블록 위에 놓습니다. 서로 겹친 부분만 다음 층으로 남고 밖으로 튀어나온 조각은 잘려 떨어집니다. 탑이 높아질수록 블록 이동 속도가 빨라집니다.',
    objective: '블록 폭이 사라지기 전에 최대한 많은 층을 쌓아 최고 기록을 만드세요.',
    theme: { background: '#6c78e8', surface: '#252866', accent: '#ffd86b', accent2: '#ff8db3', text: '#ffffff', muted: '#d4d7ff', headerStyle: 'light' },
    controls: [{ label: '탭', description: '움직이는 블록을 현재 위치에 떨어뜨립니다. 한 번 놓은 블록은 다시 움직일 수 없습니다.' }],
    scoringRules: [{ label: '새 층', value: '블록 배치 성공마다 +1점' }, { label: 'PERFECT', value: '중심 오차가 아래 블록 폭의 4% 이내면 폭을 그대로 유지' }, { label: '연속 PERFECT', value: '2연속부터 층마다 폭을 7px씩, 최대 220px까지 회복' }],
    failureConditions: ['현재 블록과 아래 블록이 전혀 겹치지 않으면 즉시 종료됩니다.'],
    tips: ['상단 BLOCK WIDTH 수치가 남은 폭을 백분율로 보여줍니다.', '블록은 층마다 빨라지므로 화면 중앙보다 아래 블록의 모서리를 기준으로 맞추는 편이 안정적입니다.', '폭이 좁아졌을 때 연속 PERFECT를 만들면 다시 회복할 수 있습니다.'],
  },
  {
    id: 'pin-core', slug: 'pin-core', title: 'Pin Core', kicker: 'FIND THE GAP', icon: 'PC', category: 'Rhythm Precision',
    shortDescription: '빈틈이 발사선에 오는 순간 탭해 회전하는 코어에 핀을 빠르게 꽂으세요.',
    fullDescription: '탭하면 핀이 다트처럼 짧고 빠르게 코어로 날아갑니다. 날아가는 경로에서는 다른 핀과 충돌하지 않으며, 코어에 닿는 순간 핀의 실제 머리와 축이 이미 꽂힌 핀에 겹치는지만 판정합니다.',
    objective: '회전하는 핀 사이의 빈틈에 새 핀을 최대한 많이 꽂으세요.',
    theme: { background: '#101114', surface: '#24252b', accent: '#ffeb37', accent2: '#ff485e', text: '#ffffff', muted: '#b6b7bd', headerStyle: 'dark' },
    controls: [{ label: '탭', description: '아래 대기 중인 핀을 즉시 발사합니다. 약 0.085초의 짧은 비행 중에는 추가 탭이 입력되지 않습니다.' }],
    scoringRules: [{ label: '장착 성공', value: '다른 핀과 겹치지 않고 코어에 꽂히면 +1점' }, { label: '아슬아슬 성공', value: '가까운 간격을 통과하면 강한 성공 연출이 발생하지만 점수는 동일하게 +1점' }, { label: '속도 변화', value: '점수가 오를수록 회전이 빨라지고 7핀마다 회전 방향 전환' }],
    failureConditions: ['핀 끝이 코어에 닿는 순간, 화면에 보이는 핀 머리나 축이 기존 핀과 실제로 겹칠 때만 종료됩니다.'],
    tips: ['비행이 매우 짧으므로 빈틈이 아래 발사선에 도착하는 순간에 맞춰 탭하세요.', '날아가는 중간에 회전 핀이 경로를 지나가도 충돌하지 않습니다.', '회전 방향이 바뀌는 7, 14, 21점 직후에는 다음 탭 전에 방향을 다시 확인하세요.'],
  },
  {
    id: 'pocket-golf', slug: 'pocket-golf', title: 'Pocket Golf', kicker: 'A TINY FAIRWAY', icon: 'PG', category: 'Mini Golf',
    scoreDirection: 'low', scoreSuffix: '타',
    shortDescription: '벽·범퍼·모래·물 장애물을 공략해 5개 홀의 총 타수를 줄이세요.',
    fullDescription: '공을 뒤로 당겨 방향과 힘을 정하고 5개의 서로 다른 미니 코스를 연속 공략합니다. 벽 반사를 활용하고 범퍼와 모래를 계산하며 물을 피하세요. 마지막 홀까지 끝낸 총 타수가 기록되며 적을수록 높은 순위입니다.',
    objective: '5개 스테이지를 완주하고 총 타수를 가능한 한 낮게 기록하세요.',
    theme: { background: '#163d31', surface: '#0c2721', accent: '#f7df73', accent2: '#ef7065', text: '#ffffff', muted: '#b9d8c6', headerStyle: 'dark' },
    controls: [{ label: '화면 누르기', description: '공이 완전히 멈췄다면 화면 어느 위치에서든 누르고 조준을 시작할 수 있습니다.' }, { label: '당겼다 놓기', description: '샷의 반대 방향으로 최대 140px까지 당긴 뒤 손을 놓습니다. 시작 위치와 관계없이 드래그 방향과 거리로 샷이 결정됩니다.' }],
    scoringRules: [{ label: '최종 기록', value: '5개 홀을 완료할 때까지 사용한 총 타수가 기록되며 낮을수록 좋습니다.' }, { label: '파(Par)', value: '각 홀의 기준 타수와 현재 홀 타수를 상단에서 비교할 수 있습니다.' }, { label: '물 장애물', value: '물에 빠지면 이전 샷 위치로 돌아가고 벌타 +1이 추가됩니다.' }],
    failureConditions: ['게임 오버는 없으며 5번 홀을 넣으면 코스가 종료되고 총 타수가 확정됩니다.'],
    tips: ['직선 길이 막혔다면 코스 벽을 이용한 뱅크샷이 더 적은 타수일 수 있습니다.', '모래에서는 공이 급격히 느려지므로 다음 샷 위치를 만들 때 활용할 수 있습니다.', '홀을 너무 빠르게 지나가면 들어가지 않으므로 마지막 샷은 힘을 줄이세요.'],
  },
  {
    id: 'axebound', slug: 'axebound', title: 'AXEBOUND', kicker: 'CLIMB THE HOLLOW', icon: 'AX', category: 'Physics Climber',
    scoreSuffix: 'm', recordOnExit: true,
    shortDescription: '도끼를 던져 암벽에 박고, 흔들리는 몸을 끌어올려 끝없는 첨탑을 정복하세요.',
    fullDescription: '화면을 드래그한 방향으로 도끼를 던집니다. 날이 바위나 나무에 올바른 각도와 속도로 닿으면 박히고, 빛나는 연결선이 몸을 물리적으로 끌어올립니다. 금속·수정·얼음·가시 바위에는 박히지 않습니다. 떨어져도 죽지 않으며 아래 지형에 자연스럽게 걸린 곳에서 즉시 다시 도전합니다.',
    objective: '체크포인트 없이 하나로 연결된 THE HOLLOW SPIRE를 끝까지 올라 정상의 빛나는 제단에 도달하세요.',
    theme: { background: '#07030e', surface: '#160821', accent: '#ffca45', accent2: '#ff359b', text: '#fff7db', muted: '#9c86ae', headerStyle: 'neon' },
    controls: [{ label: '드래그', description: '화면 어디서든 원하는 투척 방향으로 직접 드래그합니다. 선의 길이가 도끼의 힘을 결정합니다.' }, { label: '놓기', description: '손을 놓으면 도끼가 실제 중력과 회전을 받으며 날아갑니다. 18px보다 짧은 드래그는 취소됩니다.' }, { label: '세이브 던지기', description: '흔들리거나 빠르게 추락하는 중에도 새 도끼를 던져 아래쪽 암벽을 잡을 수 있습니다.' }],
    scoringRules: [{ label: '최고 높이', value: '시작 바닥 0m부터 정상 1000m까지 이번 등반에서 도달한 최고 높이를 기록' }, { label: '정상 도달', value: '정상 제단에 몸이 닿거나 도끼를 박고 가까이 올라가면 1000m 완주' }, { label: '추락', value: '점수는 유지되지만 실제 지형에 걸릴 때까지 올라온 거리를 잃음' }],
    failureConditions: ['게임 오버와 즉사는 없습니다. 잘못 던지면 아래 지형 또는 시작 바닥까지 실제로 추락합니다.'],
    tips: ['바위와 나무의 정면을 향해 충분한 속도로 날을 꽂아야 하며 손잡이 충돌이나 스치는 각도는 튕겨 나갑니다.', '도끼가 박힌 뒤 몸이 흔들리는 관성을 유지한 채 다음 도끼를 던지면 더 멀리 올라갈 수 있습니다.', '금속은 청색, 수정은 민트색, 얼음은 옅은 하늘색으로 빛나며 모두 도끼가 박히지 않습니다.', '큰 추락 중 넓은 측면 암벽을 향해 빠르게 세이브 던지기를 시도하세요.'],
  },
]

export const games: MiniGameModule[] = definitions.map((game) => ({
  ...game,
  createController: (options) => createController(game.id, game.theme, options),
}))

export const gameById = (id: string) => games.find((game) => game.id === id)
